apiVersion: v2
name: nora
description: NORA — a container registry proxy with caching and garbage collection
type: application
version: 0.1.7
appVersion: "0.6.2"
annotations:
  artifacthub.io/category: integration-delivery
home: https://github.com/getnora-io/nora
sources:
  - https://github.com/getnora-io/nora
maintainers:
  - name: getnora-io
    url: https://github.com/getnora-io
icon: https://avatars.githubusercontent.com/u/257139033?v=4
keywords:
  - registry
  - container
  - proxy
  - cache
  - oci
  - artifacts
  - docker
