apiVersion: v2
name: nora
description: NORA — a container registry proxy with caching and garbage collection
type: application
version: 0.1.3
appVersion: "0.6.1"
home: https://github.com/getnora-io/nora
sources:
  - https://github.com/getnora-io/nora
maintainers:
  - name: getnora-io
    url: https://github.com/getnora-io
icon: https://raw.githubusercontent.com/getnora-io/nora/main/logo.svg
keywords:
  - registry
  - container
  - proxy
  - cache
  - oci
  - artifacts
  - docker
